### ISSUE TITLE
Create new interactions to the bot

### ISSUE THREAD

**Issue by rickvargas** [brunohadlich/barnabot#4]
This issue is related to create new interactions related to read text and the response from the barnabot.

The suggestion will follow the structure `read text: response message`
i.e.: Nestor: Hi Nestor

The new suggestions are:
- ponteiro: Edson, o que é um ponteiro???
- Edson: Edson, me ajuda numas shared memory??
- puxa-saco: ouvi um cross blowjob??
- sogra: olha, agora eu virei amigo da minha sogra.
- carro: é dificil manter um corola
- russa: to fazendo roleta russa com as contas esse mes.

**Comment by Mastoda** [comment]
saco: "coça meu saco aqui também"

**Comment by rickvargas** [comment]
Added under commit e0fe2abb501e2550e58b20fea346b18c45b812bb.

Will implement:
- datastore: @bruno_hadlich, me ajuda a criar uma pagina nesse sistema embarcado
- ligacao + nestor: lembrei que tenho que ligar pro Nestor
- balde: mas eu prefiro um balde de merda à isso
- vagas: to conversando com 3 recrutadores
- aniversário: opa, quem paga a cuca?
